### ISSUE TITLE
Alternative to Wordpress?

### ISSUE THREAD

**Issue by kumy** [GeoKretyMap/wordpress-theme#11]
As discussed with @SammysHP, `Wordpress` may not be the good tool for:
- Collaborative work
- Managing translations
- Serving static content
- ?

Migrate to a static website generator should be envisaged.

_What could be the alternatives?_
- Jekyll (github.io hosting?)

**Comment by SammysHP** [comment]
Not necessarily a static website generator (which would be the best tool when working with git of course), but something that is not so blog-like.

**Comment by kumy** [comment]
Jekyll used and new repo published

**Comment by kumy** [comment]
https://github.com/GeoKretyMap/geokretymap.github.io
